"""init

Revision ID: 5693e13ae33a
Revises: 
Create Date: 2026-01-20 14:58:49.898500

"""
from alembic import op
import sqlalchemy as sa



revision = '5693e13ae33a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=True),
    sa.Column('video_title', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_channel_id', sa.String(length=64), nullable=True),
    sa.Column('text_raw', sa.Text(), nullable=False),
    sa.Column('text_norm', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('decision', sa.Enum('PUBLISHED', 'HELD', 'REJECTED', 'BORDERLINE', name='decision', native_enum=False), nullable=True),
    sa.Column('yt_status', sa.Enum('PUBLISHED', 'HELD_FOR_REVIEW', 'REJECTED', name='ytstatus', native_enum=False), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_video_id'), 'comments', ['video_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('pr_auc', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_targets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('CHANNEL', 'VIDEO', name='targettype', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('filter', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_targets_target'), 'monitoring_targets', ['target'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('channel_handle', sa.String(length=64), nullable=True),
    sa.Column('channel_url', sa.String(length=255), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('permission_granted', sa.Boolean(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_channel_id'), 'oauth_accounts', ['channel_id'], unique=False)
    op.create_table('pipeline_status',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED', name='pipelinestate', native_enum=False), nullable=True),
    sa.Column('last_fetch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_latency_sec', sa.Float(), nullable=True),
    sa.Column('queue_size', sa.Integer(), nullable=True),
    sa.Column('processed_last_hour', sa.Integer(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('threshold_low', sa.Float(), nullable=True),
    sa.Column('threshold_high', sa.Float(), nullable=True),
    sa.Column('borderline_enabled', sa.Boolean(), nullable=True),
    sa.Column('monitored_videos', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('theme', sa.String(length=32), nullable=True),
    sa.Column('density', sa.String(length=32), nullable=True),
    sa.Column('notify_new_comments', sa.Boolean(), nullable=True),
    sa.Column('auto_hold_suspicious', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('comment_id', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('from_decision', sa.Enum('PUBLISHED', 'HELD', 'REJECTED', 'BORDERLINE', name='decision', native_enum=False), nullable=True),
    sa.Column('to_decision', sa.Enum('PUBLISHED', 'HELD', 'REJECTED', 'BORDERLINE', name='decision', native_enum=False), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.drop_table('settings')
    op.drop_table('pipeline_status')
    op.drop_index(op.f('ix_oauth_accounts_channel_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_monitoring_targets_target'), table_name='monitoring_targets')
    op.drop_table('monitoring_targets')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_comments_video_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
