export const seedComments = [
  {
    id: "c_001",
    createdAt: "2026-01-12 09:10",
    videoTitle: "Podcast Ep 1",
    text: "Mantap banget bahasannya, lanjutkan.",
    author: "Budi Santoso",
    authorInitials: "BS",
    score: 0.12,
    decision: "PUBLISHED",
    ytStatus: "published",
  },
  {
    id: "c_002",
    createdAt: "2026-01-12 10:05",
    videoTitle: "Podcast Ep 2",
    text: "Penjelasan jelas dan gampang diikuti.",
    author: "Siti Rahayu",
    authorInitials: "SR",
    score: 0.08,
    decision: "PUBLISHED",
    ytStatus: "published",
  },
  {
    id: "c_003",
    createdAt: "2026-01-13 08:45",
    videoTitle: "Tutorial",
    text: "Terima kasih, sangat membantu.",
    author: "Ahmad Fauzi",
    authorInitials: "AF",
    score: 0.18,
    decision: "PUBLISHED",
    ytStatus: "published",
  },
  {
    id: "c_004",
    createdAt: "2026-01-13 11:20",
    videoTitle: "Live Stream",
    text: "Ada link cepat yang bisa dibagi?",
    author: "User123",
    authorInitials: "U1",
    score: 0.62,
    decision: "HELD",
    ytStatus: "heldForReview",
  },
  {
    id: "c_005",
    createdAt: "2026-01-13 12:10",
    videoTitle: "Podcast Ep 1",
    text: "Boleh titip promo?",
    author: "Rina Wati",
    authorInitials: "RW",
    score: 0.74,
    decision: "HELD",
    ytStatus: "heldForReview",
  },
  {
    id: "c_006",
    createdAt: "2026-01-13 13:40",
    videoTitle: "Tutorial",
    text: "Butuh info tambahan, ada panduan lain?",
    author: "Dina Putri",
    authorInitials: "DP",
    score: 0.68,
    decision: "HELD",
    ytStatus: "heldForReview",
  },
  {
    id: "c_007",
    createdAt: "2026-01-14 09:05",
    videoTitle: "Podcast Ep 2",
    text: "Ini jelas spam, hapus saja.",
    author: "Suspicious User",
    authorInitials: "SU",
    score: 0.9,
    decision: "REJECTED",
    ytStatus: "rejected",
  },
  {
    id: "c_008",
    createdAt: "2026-01-14 09:45",
    videoTitle: "Live Stream",
    text: "Cek bio untuk bonus besar.",
    author: "Spammer",
    authorInitials: "SP",
    score: 0.88,
    decision: "REJECTED",
    ytStatus: "rejected",
  },
  {
    id: "c_009",
    createdAt: "2026-01-14 10:30",
    videoTitle: "Tutorial",
    text: "Komentar berisi ajakan mencurigakan.",
    author: "Unknown",
    authorInitials: "UN",
    score: 0.92,
    decision: "REJECTED",
    ytStatus: "rejected",
  },
  {
    id: "c_010",
    createdAt: "2026-01-14 11:15",
    videoTitle: "Podcast Ep 1",
    text: "Sepertinya abu-abu, butuh cek lagi.",
    author: "Fajar Malik",
    authorInitials: "FM",
    score: 0.55,
    decision: "BORDERLINE",
    ytStatus: "heldForReview",
  },
  {
    id: "c_011",
    createdAt: "2026-01-14 12:00",
    videoTitle: "Podcast Ep 2",
    text: "Mungkin promosi terselubung.",
    author: "Nia Lestari",
    authorInitials: "NL",
    score: 0.66,
    decision: "BORDERLINE",
    ytStatus: "heldForReview",
  },
  {
    id: "c_012",
    createdAt: "2026-01-14 12:50",
    videoTitle: "Live Stream",
    text: "Kata-katanya agak mencurigakan.",
    author: "Gilang Prasetyo",
    authorInitials: "GP",
    score: 0.49,
    decision: "BORDERLINE",
    ytStatus: "heldForReview",
  },
]

export const seedAuditLogs = [
  {
    id: "log_a1",
    at: "2026-01-14 10:00",
    action: "DECISION_UPDATE",
    commentId: "c_007",
    score: 0.9,
    fromDecision: "HELD",
    toDecision: "REJECTED",
    actor: "admin",
    result: "OK",
    note: "Promosi jelas.",
  },
  {
    id: "log_a2",
    at: "2026-01-14 10:20",
    action: "DECISION_UPDATE",
    commentId: "c_004",
    score: 0.62,
    fromDecision: "BORDERLINE",
    toDecision: "HELD",
    actor: "admin",
    result: "OK",
    note: "Perlu review lanjutan.",
  },
  {
    id: "log_a3",
    at: "2026-01-14 10:45",
    action: "DECISION_UPDATE",
    commentId: "c_010",
    score: 0.55,
    fromDecision: "HELD",
    toDecision: "BORDERLINE",
    actor: "system",
    result: "OK",
    note: "Skor mendekati ambang.",
  },
  {
    id: "log_a4",
    at: "2026-01-14 11:00",
    action: "SETTINGS_UPDATE",
    commentId: null,
    score: null,
    fromDecision: null,
    toDecision: null,
    actor: "admin",
    result: "OK",
    note: "Settings updated",
  },
  {
    id: "log_a5",
    at: "2026-01-14 11:30",
    action: "DECISION_UPDATE",
    commentId: "c_002",
    score: 0.08,
    fromDecision: "HELD",
    toDecision: "PUBLISHED",
    actor: "admin",
    result: "OK",
    note: "Aman untuk tayang.",
  },
  {
    id: "log_a6",
    at: "2026-01-14 12:05",
    action: "DECISION_UPDATE",
    commentId: "c_008",
    score: 0.88,
    fromDecision: "HELD",
    toDecision: "REJECTED",
    actor: "admin",
    result: "OK",
    note: "Spam terkonfirmasi.",
  },
  {
    id: "log_a7",
    at: "2026-01-14 12:40",
    action: "SETTINGS_UPDATE",
    commentId: null,
    score: null,
    fromDecision: null,
    toDecision: null,
    actor: "system",
    result: "ERROR",
    note: "Validation failed",
  },
  {
    id: "log_a8",
    at: "2026-01-14 13:10",
    action: "DECISION_UPDATE",
    commentId: "c_011",
    score: 0.66,
    fromDecision: "BORDERLINE",
    toDecision: "HELD",
    actor: "admin",
    result: "OK",
    note: "Butuh verifikasi tambahan.",
  },
]

export const seedSettings = {
  thresholdLow: 0.4,
  thresholdHigh: 0.7,
  borderlineEnabled: true,
  monitoredVideos: ["Podcast Ep 1", "Tutorial"],
  language: "id",
  theme: "light",
  density: "standard",
  notifyNewComments: true,
  autoHoldSuspicious: true,
}

export const seedOAuthStatus = {
  connected: false,
  permissionGranted: false,
  accountEmail: "filamsi.admin@gmail.com",
  channelName: "",
  channelId: "",
  channelHandle: "",
  channelUrl: "",
  lastSync: "-",
  tokenExpiry: "-",
  scopes: [],
}

export const seedChannelOptions = [
  {
    id: "opt_001",
    channelId: "UC0FILAMSI123",
    name: "Kanal YouTube Saya",
    handle: "@channel_saya",
    subscribers: "10.5K",
    url: "https://www.youtube.com/@FilamsiGhifary-rz7yr",
  },
  {
    id: "opt_002",
    channelId: "UC0KANAL002",
    name: "Kanal Lainnya",
    handle: "@kanal_lain",
    subscribers: "5.2K",
    url: "https://www.youtube.com/@kanal_lain",
  },
]

export const seedMonitoringTargets = [
  {
    id: "t_001",
    type: "CHANNEL",
    label: "Kanal YouTube Saya",
    target: "UC0FILAMSI123",
    filter: "slot, gacor, bonus",
    active: true,
  },
  {
    id: "t_002",
    type: "VIDEO",
    label: "Podcast Ep 1",
    target: "vid_podcast_1",
    filter: "promo, link",
    active: true,
  },
  {
    id: "t_003",
    type: "VIDEO",
    label: "Tutorial",
    target: "vid_tutorial_1",
    filter: "daftar, deposit",
    active: true,
  },
  {
    id: "t_004",
    type: "VIDEO",
    label: "Live Stream",
    target: "vid_live_1",
    filter: "vip, bonus",
    active: false,
  },
]

export const seedModelMetrics = {
  modelName: "IndoBERTweet",
  version: "v1.2.0",
  precision: 0.93,
  recall: 0.88,
  f1: 0.9,
  prAuc: 0.91,
  avgLatencyMs: 220,
  updatedAt: "2026-01-13 18:30",
}

export const seedPipelineStatus = {
  status: "PAUSED",
  lastFetch: "-",
  avgLatencySec: 2.4,
  queueSize: 12,
  processedLastHour: 340,
  errorRate: 0.01,
}

export const seedSetupState = {
  step: 1,
  completed: false,
}
